DROP TABLE IF EXISTS USER_DETAILS;

CREATE TABLE USER_DETAILS (
  USER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) DEFAULT NULL
);